version: 2

init: &init
  run:
    name: init
    command: |
      echo '. .circleci/shared.bash' >> "$BASH_ENV"

jobs:
  build_test:
    environment:
      CC_TEST_REPORTER_ID: e70e48da820d9d23eeb2f1fd8c25f8691be05af308dd0ffce8d1ca7e48a5f799
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64/v8
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: docker -v
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - checkout
      - run:
          name: Install test reporter
          command: |
            curl -L -o "cc-test-reporter" "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
            sudo chmod +x ./cc-test-reporter
      - run: make image
      - run: make citest

  publish:
    machine: true
    steps:
      - checkout
      - *init
      - run:
          name: Install Hub dependency
          command: install_hub
      - run:
          name: Login on Dockerhub
          command: login_to_dockerhub
      - run:
          name: Login on RubyGems
          command: login_to_rubygems
      - run:
          name: Publish new version
          command: |
            if [ `git diff --quiet HEAD~ VERSION; echo $?` -eq 1 ]; then
              publish_new_version
            fi

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master

notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
